# Generated by Django 3.0.5 on 2020-08-21 07:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='player',
            name='email',
        ),
        migrations.RemoveField(
            model_name='player',
            name='name',
        ),
        migrations.AddField(
            model_name='player',
            name='profile_pic',
            field=models.ImageField(default='images/profile-icon.jpg', upload_to='images'),
        ),
        migrations.AddField(
            model_name='player',
            name='total_score',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('win', models.CharField(blank=True, max_length=200, null=True)),
                ('loss', models.CharField(blank=True, max_length=200, null=True)),
                ('draw', models.BooleanField(null=True)),
                ('players', models.ManyToManyField(to='main.Player')),
            ],
        ),
    ]
