# Generated by Django 3.0.5 on 2020-08-21 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200821_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='play_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='matches',
            name='players',
            field=models.ManyToManyField(to='main.Player'),
        ),
    ]
