# Generated by Django 3.0.5 on 2020-08-21 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200821_1200'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Matches',
        ),
        migrations.DeleteModel(
            name='player',
        ),
    ]
