# Generated by Django 3.0.5 on 2020-08-22 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_auto_20200821_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(default='images/profile-icon.jpg', upload_to='images')),
                ('total_score', models.IntegerField(null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('play_time', models.DateTimeField(auto_now=True, null=True)),
                ('win', models.CharField(blank=True, max_length=200, null=True)),
                ('loss', models.CharField(blank=True, max_length=200, null=True)),
                ('draw', models.BooleanField(null=True)),
                ('players', models.ManyToManyField(to='main.Player')),
            ],
        ),
    ]
