# Generated by Django 3.0.5 on 2020-08-26 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200825_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='draw_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='loss_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='matches_played',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='win_count',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
